apiVersion: v1
kind: Namespace
metadata:
  name: ai-chatbot
---
apiVersion: v1
kind: Secret
metadata:
  name: llm-api-keys
  namespace: ai-chatbot
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://aritrasharma96542_db_user:REPLACE_WITH_NEW_PASSWORD@chatbotcluster.nq7mgjp.mongodb.net/ai_chatbot?appName=chatbotcluster"
  OPENAI_API_KEY: "sk-..."
  ANTHROPIC_API_KEY: "sk-ant-..."
  GOOGLE_API_KEY: "AIza..."
  DEEPSEEK_API_KEY: "sk-..."
  GROK_API_KEY: "xai-..."
